version: '3'

services:
  vacation-backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: VacationsDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
